# Generated by Django 5.1.3 on 2025-04-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingpassage',
            name='order_id',
            field=models.IntegerField(default=1),
        ),
    ]
