---
deployment:
  tasks:
    - export DEPLOY_ENVIRONMENT=production
    - python -m venv venv
    - venv\Scripts\activate
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py collectstatic --noinput
