# Generated by Django 5.1.3 on 2025-02-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answerkey_create', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ssc_cgl_2024_answerkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
